### PR TITLE
Feature_Adds more db seeds and db updates 

### PR DESCRIPTION
**Pull request by Oh-KPond**
Steps to getting this running:

1. Switch to branch
2. run `rails db:migrate:status`
3. run `rails db:migrate`
4. run `rails db:reset`

You may find that some seeds are not created. This is due to Faker making some duplications and the validations kicking those records out. This is expected at this point.

The models have been updated as well, but they don't see to be showing up in the diff below. We can talk about the changes before we merge.

### CODE REVIEW

**Comment by brittanyrjones** [comment]
I am hoping that all of us can review these changes and add any input before we move on.

**Comment by Oh-KPond** [comment]
I agree with you @brittanyrjones ✅

**Comment by brittanyrjones** [comment]
Hey So i am seeing a few errors, please dont merge this quite yet, I forgot the fix the alphabet order name in the table and i dropped a table i shouldnt have. WIll update when it is fixed

**Comment by Oh-KPond** [comment]
Learning experiences!! 😄

**Comment by lillers1122** [comment]
So good! Quick note: orders_products yml file name should be changed to order_items before merge

**Pull request merged**
